webserver:
  # changer la version selon le no du build
 image: nmolleruq/moouqamtest:0.0.30  

 environment:
   MDL_DBTYPE: mysqli
   MDL_DBHOST: mysqlserver
   MDL_DBNAME: coursv3
   MDL_DBUSER: root
   MDL_DBPASS: root
   MDL_WWWROOT: 'http://localhost:8180'
   MDL_MEMSESSION: memsession
   MDL_DATAROOT: '/var/www/moodledata'
   MDL_LOCALCACHEDIR: '/tmp/moodle'

 links:
   - mysqlserver
   - memsession

 ports:
   - "8180:80"

mysqlserver:
    image: heathrow/mysql:5.7 #mysql:5.6
    # Besoin de plus de paramètres
    environment:
      MYSQL_DATABASE: coursv3
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARSET: utf8mb4 
      MYSQL_COLLATION: utf8mb4_general_ci 
      MYSQL_INNODB_LARGE_PREFIX: 1
  
memsession:
  image: memcached
